name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install compactc
        env:
          COMPACT_VERSION: 0.24.0
        run: |
          export PATH=${PWD}:$PATH
          echo "PATH=${PWD}:$PATH" >> $GITHUB_ENV
          wget https://d3fazakqrumx6p.cloudfront.net/artifacts/compiler/compactc_${COMPACT_VERSION}/compactc_v${COMPACT_VERSION}_x86_64-unknown-linux-musl.zip
          unzip ./compactc_v${COMPACT_VERSION}_x86_64-unknown-linux-musl.zip
          rm ./compactc_v${COMPACT_VERSION}_x86_64-unknown-linux-musl.zip
          compactc --version

      - name: Compile and test contract
        working-directory: contract
        run: |
          npm run lint
          npm run compact
          npm run typecheck
          npm run build
          npm run test

      - name: Compile counter-cli
        working-directory: counter-cli
        run: |
          npm run lint
          npm run typecheck
          npm run build
          npm run test-api
